name: xplatform
channels:
  - defaults
dependencies:
  - tqdm
  - jupyter
  - python-graphviz
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - numpy
  - xlrd
  - matplotlib-venn
  - scikit-learn
  - adjusttext
  - graphviz
